## Description: Create Seurat object using data from Andrew Ji's GEO data
## Note: RNA_counts_sparse_matrix.rds was generated by loading the GSE144236_cSCC_counts.txt.gz
## file with fread on Sherlock and then converting to matrix with as.matrix and then a sparse
## matrix with Matrix(x, sparse=T)

library(Seurat)
library(readr)
library(dplyr)

dataDir <- file.path("data", "ji-2019")
cellMetadata <- read.table(file.path(dataDir, "GSE144236_patient_metadata_new.txt.gz"))
genes <- readRDS("data/ji-2019/RNA_genes.rds")
expMat <- readRDS("data/ji-2019/RNA_counts_sparse_matrix.rds")
rownames(expMat) <- genes

cells <- CreateSeuratObject(
  counts = expMat,
  meta.data = cellMetadata
)

# Remove multiplets - not of use to us
cells <- subset(cells, level1_celltype != "Multiplet")

cells[["percent.mt"]] <- PercentageFeatureSet(cells, pattern = "^MT-")


cells <- NormalizeData(cells)
cells <- FindVariableFeatures(cells)
cells <- ScaleData(cells)
cells <- RunPCA(cells)
cells <- FindNeighbors(cells)
cells <- RunUMAP(cells, dims = 1:50)



saveRDS(cells, file.path(dataDir, "Ji_2019_Cells.rds"))
